import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SemnaticLayout from "@/components/semantic-layout";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "chat-bot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SemnaticLayout>{children}</SemnaticLayout>
      </body>
    </html>
  );
}
